const bios = [
  "Dreamer, doer, and a lifelong learner.",
  "Curious mind wandering in a world of possibilities.",
  "Just another soul turning coffee into code.",
  "Designing today, dreaming of tomorrow.",
  "On a mission to build cool things and break limits.",
  "Learning one bug at a time.",
  "Tech enthusiast with a twist of creativity.",
  "Gamer by night, coder by day.",
  "Running on caffeine and curiosity.",
  "Turning ideas into digital reality.",
  "Small progress is still progress.",
  "Exploring the digital world, one click at a time.",
  "Builder of dreams and fixer of bugs.",
  "Living life one playlist at a time.",
  "Debugging life, line by line.",
  "Big ideas, small steps, endless growth.",
  "Fluent in memes, mistakes, and motivation.",
  "Passion-fueled and purpose-driven.",
  "Learning AI so it doesn’t learn me first.",
  "Writing code like it's poetry (but messier).",
  "Making pixels dance and servers sing.",
  "Scripting life, one function at a time.",
  "Weekend warrior, weekday wireframer.",
  "In beta — just like my projects.",
  "Building the future with broken keyboards.",
  "Code whisperer with a side of chaos.",
  "Fuelled by deadlines and dreams.",
  "Ctrl+Z is my safety net.",
  "Creativity is my favorite bug.",
  "Half human, half syntax error.",
  "Putting the 'fun' in 'function'.",
  "Writing bugs faster than you can say 'merge conflict'.",
  "Somewhere between stack overflow and spiritual awakening.",
  "90% caffeine, 10% logic.",
  "Procrastinator with a productivity playlist.",
  "Code now, cry later.",
  "Design, deploy, debug, repeat.",
  "WiFi is my love language.",
  "Living on the edge of innovation (and burnout).",
  "Glitching through life with grace.",
  "Loading... a better version of myself.",
  "Here to make bugs feel seen.",
  "Not a robot... yet.",
  "Engineering chaos into creativity.",
  "Saving the world, one commit at a time.",
  "Passionate about pixels and perfection.",
  "Trying to outsmart yesterday's self.",
  "The code works… don’t touch it!",
  "Running on dark mode and determination.",
  "Crafting clean code and messy buns.",
  "Waiting for inspiration… and internet.",
  "Turning caffeine into innovation since forever.",
  "Walking the fine line between genius and typo.",
  "Debugging reality with imagination.",
  "Version control applies to my personality too.",
  "Creativity runs in my command line.",
  "Escaping semicolon errors and existential dread.",
  "Spinning thoughts into threads (and loops).",
  "Multitasking through bugs and breakfast.",
  "Auto-saving my sanity.",
  "Living in a constant state of update.",
  "Still figuring it out — and that’s okay.",
  "Code. Coffee. Repeat.",
  "Syntax over stress.",
  "I void warranties and expectations.",
  "Mood: currently refactoring everything.",
  "Actively compiling my life choices.",
  "Here for the logic, staying for the chaos.",
  "Mastering the art of last-minute fixes.",
];

export const getRandomBio = () => {
  return bios[Math.floor(Math.random() * bios.length)];
};
